#!/usr/bin/env bun
/**
 * Regenerates src/icons/nucleo/{ui,pixel}.tsx from a licensed Nucleo install.
 *
 *   NUCLEO_DIR=~/.nucleo/skills bun scripts/vendor-nucleo.ts && bunx oxfmt src/icons/nucleo
 *
 * Nucleo allows at most 100 icons in an open-source project, with its copyright notice;
 * the vendored files are under the Nucleo License, not Apache-2.0 (see src/icons/nucleo).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const NUCLEO_DIR = process.env["NUCLEO_DIR"] ?? join(homedir(), ".nucleo/skills");

const OUT = join(import.meta.dir, "../src/icons/nucleo");

/** Polaris name → Nucleo UI outline 18px component. Chrome icons (DESIGN.md, Icons). */
const UI: ReadonlyArray<readonly [string, string]> = [
  ["SearchIcon", "MagnifierOutline18"],
  ["PlusIcon", "PlusOutline18"],
  ["ChevronDownIcon", "ChevronDownOutline18"],
  ["ChevronUpIcon", "ChevronUpOutline18"],
  ["ChevronRightIcon", "ChevronRightOutline18"],
  ["CheckIcon", "CheckOutline18"],
  ["CloseIcon", "XmarkOutline18"],
  ["FolderIcon", "FolderOutline18"],
  ["ArrowUpIcon", "ArrowUpOutline18"],
  ["StopIcon", "MediaStopOutline18"],
  ["ThumbUpIcon", "ThumbsUpOutline18"],
  ["ThumbDownIcon", "ThumbsDownOutline18"],
  ["BranchIcon", "CodeBranchOutline18"],
];

/** Polaris name → Nucleo pixel outline 24px component. Polaris-owned concepts only. */
const PIXEL: ReadonlyArray<readonly [string, string]> = [
  ["PixelHandIcon", "HandOutline24"],
  ["PixelTerminalIcon", "SquareTerminalOutline24"],
  ["PixelFailedIcon", "CircleXmarkOutline24"],
  ["PixelKeyIcon", "KeyOutline24"],
  ["PixelFolderIcon", "FolderOutline24"],
  ["PixelServerIcon", "ServerOutline24"],
  ["PixelForkIcon", "CodeForkOutline24"],
  ["PixelArchiveIcon", "BoxArchiveOutline24"],
  ["PixelSparkleIcon", "SparkleOutline24"],
  ["PixelCheckIcon", "CheckOutline24"],
];

function inner(family: string, component: string): string {
  const source = readFileSync(join(NUCLEO_DIR, family, "components", `${component}.tsx`), "utf8");
  const match = /<svg[^>]*\{\.\.\.props\}>([\s\S]*)<\/svg>/.exec(source);

  if (match?.[1] === undefined) throw new Error(`no <svg> body in ${family}/${component}`);

  return match[1].replace(/>\s+</g, "><").replace(/ data-color="color-2"/g, "");
}

const HEADER = `// Nucleo icons, Copyright © Nucleo (nucleoapp.com). Nucleo License, not Apache-2.0: see ./LICENSE.md.
// Generated by scripts/vendor-nucleo.ts; do not edit by hand.
`;

function uiFile(): string {
  const icons = UI.map(
    ([name, component]) => `
/** Nucleo UI outline \`${component}\`. */
export function ${name}({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 18 18" aria-hidden="true" focusable="false" {...props}>
      ${inner("ui", component)}
    </svg>
  );
}
`
  );

  return `${HEADER}import type { SVGProps } from "react";

export type NucleoIconProps = SVGProps<SVGSVGElement> & { readonly size?: number };

/** 18px artwork drawn at 16px: 1.125 renders DESIGN.md's 1px stroke. */
const STROKE = 1.125;
${icons.join("")}`;
}

interface PixelPath {
  readonly d: string;
  readonly square: boolean;
  readonly miter: boolean;
}

/** Nucleo's pixel icons are all 2px stroked paths, so they vendor as a table of paths. */
function pixelPaths(component: string): PixelPath[] {
  const body = inner("pixel", component);

  const paths = [...body.matchAll(/<path ([^>]*)>/g)].map(([, attributes = ""]) => {
    const d = /\bd="([^"]+)"/.exec(attributes)?.[1];

    if (d === undefined || !attributes.includes('stroke="currentColor" strokeWidth={2}')) {
      throw new Error(`${component}: not a 2px stroked path: ${attributes}`);
    }

    return {
      d,
      square: attributes.includes('strokeLinecap="square"'),
      miter: attributes.includes('strokeMiterlimit="10"'),
    };
  });

  if (body.replace(/<path [^>]*><\/path>/g, "") !== "")
    throw new Error(`${component}: not only paths`);

  return paths;
}

function pixelFile(): string {
  const tables = PIXEL.map(([name, component]) => {
    const table = `${name
      .replace(/^Pixel|Icon$/g, "")
      .replace(/([a-z])([A-Z])/g, "$1_$2")
      .toUpperCase()}_PATHS`;

    const rows = pixelPaths(component).map(
      (path) =>
        `  ${JSON.stringify(path.d)}${path.square ? "" : " + BUTT"}${path.miter ? " + MITER" : ""},`
    );

    return `
/** Nucleo pixel \`${component}\`. */
export function ${name}(props: NucleoIconProps) {
  return <Pixels paths={${table}} {...props} />;
}

const ${table} = [
${rows.join("\n")}
];
`;
  });

  return `${HEADER}import { cn } from "../../lib/cn";
import type { NucleoIconProps } from "./ui";

/** Path suffixes: a butt cap instead of square, and Nucleo's miter limit of 10. */
const BUTT = "|butt";

const MITER = "|miter";

interface PixelsProps extends NucleoIconProps {
  readonly paths: readonly string[];
}

function Pixels({ paths, size = 16, className, ...props }: PixelsProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      aria-hidden="true"
      focusable="false"
      className={cn("pixelated", className)}
      {...props}
    >
      {paths.map((path, index) => {
        const [d, ...flags] = path.split("|");

        return (
          <path
            key={index}
            d={d}
            strokeLinecap={flags.includes("butt") ? "butt" : "square"}
            strokeMiterlimit={flags.includes("miter") ? 10 : undefined}
          />
        );
      })}
    </svg>
  );
}
${tables.join("")}`;
}

writeFileSync(join(OUT, "ui.tsx"), uiFile());

writeFileSync(join(OUT, "pixel.tsx"), pixelFile());

console.log(`vendored ${UI.length + PIXEL.length} Nucleo icons into ${OUT}`);
