/** The 16x16 Polaris star's cells, with no React: the menu bar draws it in the main process. */
export type Cell = readonly [x: number, y: number];

const STAR_HALF: ReadonlyMap<number, number> = new Map([
  [7.5, 1],
  [6.5, 1],
  [5.5, 1],
  [4.5, 2],
  [3.5, 2],
  [2.5, 3],
  [1.5, 4],
  [0.5, 8],
]);

/** The 16x16 Polaris star, as generated by gen_dither.py's star_cells(). */
export function starCells(): Cell[] {
  const cells = new Map<string, Cell>();
  const add = (x: number, y: number) => cells.set(`${x}.${y}`, [x, y]);

  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      const dx = Math.abs(x - 7.5);
      const dy = Math.abs(y - 7.5);

      if (dx < (STAR_HALF.get(dy) ?? 0) || dy < (STAR_HALF.get(dx) ?? 0)) add(x, y);
    }
  }

  for (const d of [3, 4]) {
    add(d, d);
    add(15 - d, d);
    add(d, 15 - d);
    add(15 - d, 15 - d);
  }

  return [...cells.values()];
}
