// Nucleo icons, Copyright © Nucleo (nucleoapp.com). Nucleo License, not Apache-2.0: see ./LICENSE.md.
// Generated by scripts/vendor-nucleo.ts; do not edit by hand.
import { cn } from "../../lib/cn";
import type { NucleoIconProps } from "./ui";

/** Path suffixes: a butt cap instead of square, and Nucleo's miter limit of 10. */
const BUTT = "|butt";

const MITER = "|miter";

interface PixelsProps extends NucleoIconProps {
  readonly paths: readonly string[];
}

function Pixels({ paths, size = 16, className, ...props }: PixelsProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      aria-hidden="true"
      focusable="false"
      className={cn("pixelated", className)}
      {...props}
    >
      {paths.map((path, index) => {
        const [d, ...flags] = path.split("|");

        return (
          <path
            key={index}
            d={d}
            strokeLinecap={flags.includes("butt") ? "butt" : "square"}
            strokeMiterlimit={flags.includes("miter") ? 10 : undefined}
          />
        );
      })}
    </svg>
  );
}

/** Nucleo pixel `HandOutline24`. */
export function PixelHandIcon(props: NucleoIconProps) {
  return <Pixels paths={HAND_PATHS} {...props} />;
}

const HAND_PATHS = [
  "M19 21V7",
  "M16 10V5H17",
  "M13 10L13 3H14",
  "M10 10V1H11",
  "M7 12V3H10",
  "M4 10V16",
  "M6 18L6 18.01",
  "M8 20V21",
];

/** Nucleo pixel `SquareTerminalOutline24`. */
export function PixelTerminalIcon(props: NucleoIconProps) {
  return <Pixels paths={TERMINAL_PATHS} {...props} />;
}

const TERMINAL_PATHS = [
  "M13 16H17",
  "M19 3H5",
  "M19 21H5",
  "M3 19V5",
  "M21 19V5",
  "M11.01 12L11 12",
  "M9.01001 14L9.00001 14",
  "M7.01001 16L7.00001 16",
  "M7.01001 8L7.00001 8",
  "M9.00999 10L8.99999 10",
];

/** Nucleo pixel `CircleXmarkOutline24`. */
export function PixelFailedIcon(props: NucleoIconProps) {
  return <Pixels paths={FAILED_PATHS} {...props} />;
}

const FAILED_PATHS = [
  "M8 22L16 22",
  "M18.01 20L18 20",
  "M6.01001 20L6.00001 20",
  "M20.01 18L20 18",
  "M4.01001 18L4.00001 18",
  "M16.01 16L16 16",
  "M8.01001 16L8.00001 16",
  "M14.01 14L14 14",
  "M10.01 14L10 14",
  "M12.01 12L12 12",
  "M14.01 10L14 10",
  "M10.01 10L10 10",
  "M22 8L22 16",
  "M16.01 8L16 8",
  "M8.01001 8L8.00001 8",
  "M2 8L2 16",
  "M20.01 6L20 6",
  "M4 6L4 6.01",
  "M18.01 4L18 4",
  "M6 4L6 4.01",
  "M8 2L16 2",
];

/** Nucleo pixel `KeyOutline24`. */
export function PixelKeyIcon(props: NucleoIconProps) {
  return <Pixels paths={KEY_PATHS} {...props} />;
}

const KEY_PATHS = [
  "M7 17V17.01",
  "M18 3H21V6",
  "M19 8H17V10",
  "M15 12.01V12",
  "M16 5.00998V4.99998",
  "M14 7.00998V6.99998",
  "M12 9.00998V8.99998",
  "M10 11L5 11",
  "M13 14L13 19",
  "M3 13V19",
  "M11 21L5 21",
];

/** Nucleo pixel `FolderOutline24`. */
export function PixelFolderIcon(props: NucleoIconProps) {
  return <Pixels paths={FOLDER_PATHS} {...props} />;
}

const FOLDER_PATHS = [
  "M20 7H14" + MITER,
  "M12 5H12.01",
  "M4 20H20" + MITER,
  "M4 3H10" + MITER,
  "M2 18L2 5" + MITER,
  "M22 18L22 9" + MITER,
];

/** Nucleo pixel `ServerOutline24`. */
export function PixelServerIcon(props: NucleoIconProps) {
  return <Pixels paths={SERVER_PATHS} {...props} />;
}

const SERVER_PATHS = [
  "M17 6.5V6.49",
  "M13 6.5V6.49",
  "M17 17.5V17.49",
  "M13 17.5V17.49",
  "M5 3L19 3",
  "M5 10L19 10",
  "M5 14L19 14",
  "M5 21L19 21",
  "M3 16V19",
  "M21 16V19",
  "M21 5V8",
  "M3 5V8",
];

/** Nucleo pixel `CodeForkOutline24`. */
export function PixelForkIcon(props: NucleoIconProps) {
  return <Pixels paths={FORK_PATHS} {...props} />;
}

const FORK_PATHS = [
  "M7 7V10",
  "M17 7V10",
  "M12 12V17" + BUTT,
  "M6.5 2H7.5",
  "M6.5 7H7.5",
  "M9.5 4L9.5 5",
  "M4.5 4L4.5 5",
  "M16.5 2H17.5",
  "M16.5 7H17.5",
  "M19.5 4L19.5 5",
  "M14.5 4L14.5 5",
  "M11.5 17H12.5",
  "M11.5 22H12.5",
  "M14.5 19L14.5 20",
  "M9.5 19L9.5 20",
  "M12 12V15",
  "M9 12H15",
];

/** Nucleo pixel `BoxArchiveOutline24`. */
export function PixelArchiveIcon(props: NucleoIconProps) {
  return <Pixels paths={ARCHIVE_PATHS} {...props} />;
}

const ARCHIVE_PATHS = [
  "M14 12L10 12" + MITER,
  "M21 12L21 19" + MITER,
  "M22 5L22 6" + MITER,
  "M2 5L2 6" + MITER,
  "M3 12L3 19" + MITER,
  "M19 21L5 21" + MITER,
  "M20 3L4 3" + MITER,
  "M20 8L4 8" + MITER,
];

/** Nucleo pixel `SparkleOutline24`. */
export function PixelSparkleIcon(props: NucleoIconProps) {
  return <Pixels paths={SPARKLE_PATHS} {...props} />;
}

const SPARKLE_PATHS = [
  "M10.01 7L10 7",
  "M19.01 3L19 3",
  "M19.01 7L19 7",
  "M17.01 5L17 5",
  "M21.01 5L21 5",
  "M5.01001 17L5.00001 17",
  "M5.01001 21L5.00001 21",
  "M3.01001 19L3.00001 19",
  "M7.01001 19L7.00001 19",
  "M4.01001 11L4.00001 11",
  "M6.01001 7L6.00001 7",
  "M8 3L8 5",
  "M8 9L8 11",
  "M15 9L15 11",
  "M15 19L15 21",
  "M11 15V15.01",
  "M17 13V13.01",
  "M13 13V13.01",
  "M13 17V17.01",
  "M17 17V17.01",
  "M19 15V15.01",
];

/** Nucleo pixel `CheckOutline24`. */
export function PixelCheckIcon(props: NucleoIconProps) {
  return <Pixels paths={CHECK_PATHS} {...props} />;
}

const CHECK_PATHS = [
  "M9.99999 18H10.01",
  "M12 16H12.01",
  "M7.99999 16H8.00999",
  "M14 14H14.01",
  "M5.99999 14H6.00999",
  "M3.99999 12H4.00999",
  "M22 6H22.01",
  "M16 12H16.01",
  "M18 10H18.01",
  "M20 8H20.01",
];
