// Nucleo icons, Copyright © Nucleo (nucleoapp.com). Nucleo License, not Apache-2.0: see ./LICENSE.md.
// Generated by scripts/vendor-nucleo.ts; do not edit by hand.
import type { NucleoIconProps } from "./ui";

/** 18px artwork drawn at 16px: 1.125 renders DESIGN.md's 1px stroke. */
const STROKE = 1.125;

/** Nucleo UI outline `ChevronLeftOutline18`. */
export function ChevronLeftIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <polyline
        points="11.5 15.25 5.25 9 11.5 2.75"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></polyline>
    </svg>
  );
}

/** Nucleo UI outline `GearOutline18`. */
export function GearIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path
        d="M9 11.2495C10.2426 11.2495 11.25 10.2422 11.25 8.99951C11.25 7.75687 10.2426 6.74951 9 6.74951C7.75736 6.74951 6.75 7.75687 6.75 8.99951C6.75 10.2422 7.75736 11.2495 9 11.2495Z"
        stroke="currentColor"
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
        fill="none"
      ></path>
      <path
        d="M16.25 9.35449V8.6445C16.25 8.1345 15.867 7.70651 15.36 7.65051L14.266 7.5285L13.763 6.31451L14.451 5.45551C14.769 5.05751 14.738 4.4845 14.377 4.1235L13.875 3.62149C13.515 3.26149 12.941 3.22949 12.543 3.54749L11.684 4.2355L10.47 3.73251L10.348 2.63849C10.292 2.13249 9.86405 1.7485 9.35405 1.7485H8.64405C8.13405 1.7485 7.70605 2.13149 7.65005 2.63849L7.52805 3.73251L6.31404 4.2355L5.45505 3.54849C5.05705 3.23049 4.48405 3.2615 4.12305 3.6225L3.62104 4.12451C3.26104 4.48451 3.22905 5.05851 3.54705 5.45651L4.23505 6.31549L3.73204 7.52951L2.63805 7.65149C2.13205 7.70749 1.74805 8.13551 1.74805 8.64551V9.3555C1.74805 9.8655 2.13105 10.2935 2.63805 10.3495L3.73204 10.4715L4.23505 11.6855L3.54805 12.5445C3.23005 12.9425 3.26105 13.5165 3.62205 13.8765L4.12405 14.3785C4.48405 14.7385 5.05805 14.7705 5.45605 14.4525L6.31504 13.7645L7.52905 14.2675L7.65105 15.3615C7.70705 15.8675 8.13505 16.2515 8.64505 16.2515H9.35505C9.86505 16.2515 10.293 15.8685 10.349 15.3615L10.471 14.2675L11.685 13.7645L12.544 14.4525C12.942 14.7705 13.515 14.7395 13.876 14.3785L14.378 13.8765C14.738 13.5165 14.77 12.9425 14.452 12.5445L13.765 11.6855L14.268 10.4715L15.362 10.3495C15.868 10.2935 16.252 9.8655 16.252 9.3555L16.25 9.35449Z"
        stroke="currentColor"
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
        fill="none"
      ></path>
    </svg>
  );
}

/** Nucleo UI outline `ContrastOutline18`. */
export function ContrastIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <line
        x1="9"
        y1="9"
        x2="16.249"
        y2="9"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="9"
        y1="5.25"
        x2="15.205"
        y2="5.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="9"
        y1="12.75"
        x2="15.207"
        y2="12.75"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="9"
        y1="1.75"
        x2="9"
        y2="16.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <circle
        cx="9"
        cy="9"
        r="7.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></circle>
    </svg>
  );
}

/** Nucleo UI outline `GridOutline18`. */
export function GridIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <rect
        x="2.75"
        y="2.75"
        width={4.5}
        height={4.5}
        rx="1"
        ry="1"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
      <rect
        x="10.75"
        y="2.75"
        width={4.5}
        height={4.5}
        rx="1"
        ry="1"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
      <rect
        x="2.75"
        y="10.75"
        width={4.5}
        height={4.5}
        rx="1"
        ry="1"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
      <rect
        x="10.75"
        y="10.75"
        width={4.5}
        height={4.5}
        rx="1"
        ry="1"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
    </svg>
  );
}

/** Nucleo UI outline `ChartColumnOutline18`. */
export function ChartColumnIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <line
        x1="13.25"
        y1="3.75"
        x2="13.25"
        y2="11.75"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="6.25"
        y1="6.75"
        x2="6.25"
        y2="11.75"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="9.75"
        y1="9.75"
        x2="9.75"
        y2="11.75"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <path
        d="M2.75,2.75V12.75c0,1.105,.895,2,2,2H15.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></path>
    </svg>
  );
}

/** Nucleo UI outline `ServerOutline18`. */
export function ServerIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <circle cx="4.25" cy="5.25" r=".75" fill="currentColor" data-stroke="none"></circle>
      <circle cx="6.75" cy="5.25" r=".75" fill="currentColor" data-stroke="none"></circle>
      <circle cx="4.25" cy="12.75" r=".75" fill="currentColor" data-stroke="none"></circle>
      <circle cx="6.75" cy="12.75" r=".75" fill="currentColor" data-stroke="none"></circle>
      <rect
        x="1.75"
        y="2.75"
        width={14.5}
        height={5}
        rx="1.5"
        ry="1.5"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
      <rect
        x="1.75"
        y="10.25"
        width={14.5}
        height={5}
        rx="1.5"
        ry="1.5"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
    </svg>
  );
}

/** Nucleo UI outline `SquareTerminalOutline18`. */
export function TerminalIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <rect
        x="2.75"
        y="2.75"
        width={12.5}
        height={12.5}
        rx="2"
        ry="2"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
      <line
        x1="9.75"
        y1="12.25"
        x2="12.25"
        y2="12.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <polyline
        points="5.75 12.25 8.25 9.75 5.75 7.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></polyline>
    </svg>
  );
}

/** Nucleo UI outline `ArrowUpRightOutline18`. */
export function ArrowUpRightIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <line
        x1="14.25"
        y1="3.75"
        x2="3.75"
        y2="14.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <polyline
        points="8.24 3.75 14.25 3.75 14.25 9.76"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></polyline>
    </svg>
  );
}

/** Nucleo UI outline `Paperclip2Outline18`. */
export function PaperclipIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path
        d="M10.985,5.422l-4.773,4.773c-.586,.586-.586,1.536,0,2.121h0c.586,.586,1.536,.586,2.121,0l4.95-4.95c1.172-1.172,1.172-3.071,0-4.243h0c-1.172-1.172-3.071-1.172-4.243,0l-4.95,4.95c-1.757,1.757-1.757,4.607,0,6.364h0c1.757,1.757,4.607,1.757,6.364,0l4.773-4.773"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></path>
    </svg>
  );
}
