// Nucleo icons, Copyright © Nucleo (nucleoapp.com). Nucleo License, not Apache-2.0: see ./LICENSE.md.
// Generated by scripts/vendor-nucleo.ts; do not edit by hand.
import type { SVGProps } from "react";

export type NucleoIconProps = SVGProps<SVGSVGElement> & { readonly size?: number };

/** 18px artwork drawn at 16px: 1.125 renders DESIGN.md's 1px stroke. */
const STROKE = 1.125;

/** Nucleo UI outline `MagnifierOutline18`. */
export function SearchIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path
        d="M15.75 15.75L11.6386 11.6386"
        stroke="currentColor"
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
        fill="none"
      ></path>
      <path
        d="M7.75 13.25C10.7875 13.25 13.25 10.7875 13.25 7.75C13.25 4.7125 10.7875 2.25 7.75 2.25C4.7125 2.25 2.25 4.7125 2.25 7.75C2.25 10.7875 4.7125 13.25 7.75 13.25Z"
        stroke="currentColor"
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
        fill="none"
      ></path>
    </svg>
  );
}

/** Nucleo UI outline `PlusOutline18`. */
export function PlusIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <line
        x1="9"
        y1="3.25"
        x2="9"
        y2="14.75"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="3.25"
        y1="9"
        x2="14.75"
        y2="9"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
    </svg>
  );
}

/** Nucleo UI outline `ChevronDownOutline18`. */
export function ChevronDownIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <polyline
        points="15.25 6.5 9 12.75 2.75 6.5"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></polyline>
    </svg>
  );
}

/** Nucleo UI outline `ChevronUpOutline18`. */
export function ChevronUpIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <polyline
        points="2.75 11.5 9 5.25 15.25 11.5"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></polyline>
    </svg>
  );
}

/** Nucleo UI outline `ChevronRightOutline18`. */
export function ChevronRightIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <polyline
        points="6.5 2.75 12.75 9 6.5 15.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></polyline>
    </svg>
  );
}

/** Nucleo UI outline `CheckOutline18`. */
export function CheckIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <polyline
        points="2.75 9.25 6.75 14.25 15.25 3.75"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></polyline>
    </svg>
  );
}

/** Nucleo UI outline `XmarkOutline18`. */
export function CloseIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <line
        x1="14"
        y1="4"
        x2="4"
        y2="14"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="4"
        y1="4"
        x2="14"
        y2="14"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
    </svg>
  );
}

/** Nucleo UI outline `FolderOutline18`. */
export function FolderIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path
        d="M2.25,8.75V4.75c0-1.105,.895-2,2-2h1.951c.607,0,1.18,.275,1.56,.748l.603,.752h5.386c1.105,0,2,.895,2,2v2.844"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></path>
      <path
        d="M4.25,6.75H13.75c1.105,0,2,.895,2,2v4.5c0,1.105-.895,2-2,2H4.25c-1.105,0-2-.895-2-2v-4.5c0-1.105,.895-2,2-2Z"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></path>
    </svg>
  );
}

/** Nucleo UI outline `ArrowUpOutline18`. */
export function ArrowUpIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <line
        x1="9"
        y1="2.75"
        x2="9"
        y2="15.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <polyline
        points="4.75 7 9 2.75 13.25 7"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></polyline>
    </svg>
  );
}

/** Nucleo UI outline `MediaStopOutline18`. */
export function StopIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <rect
        x="2.75"
        y="2.75"
        width={12.5}
        height={12.5}
        rx="2"
        ry="2"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
    </svg>
  );
}

/** Nucleo UI outline `ThumbsUpOutline18`. */
export function ThumbUpIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path
        d="M5.25,7.494c0-.48,.173-.944,.486-1.307L10,1.25h0c.854,.427,1.25,1.428,.92,2.324l-1.17,3.176h4.402c1.313,0,2.269,1.243,1.933,2.512l-1.191,4.5c-.232,.877-1.026,1.488-1.933,1.488H7.25c-1.105,0-2-.895-2-2"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></path>
      <rect
        x="1.75"
        y="6.75"
        width={3.5}
        height={8.5}
        rx="1"
        ry="1"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
    </svg>
  );
}

/** Nucleo UI outline `ThumbsDownOutline18`. */
export function ThumbDownIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path
        d="M5.25,10.506c0,.48,.173,.944,.486,1.307l4.264,4.937h0c.854-.427,1.25-1.428,.92-2.324l-1.17-3.176h4.402c1.313,0,2.269-1.243,1.933-2.512l-1.191-4.5c-.232-.877-1.026-1.488-1.933-1.488H7.25c-1.105,0-2,.895-2,2"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></path>
      <rect
        x="1.75"
        y="2.75"
        width={3.5}
        height={8.5}
        rx="1"
        ry="1"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></rect>
    </svg>
  );
}

/** Nucleo UI outline `CodeBranchOutline18`. */
export function BranchIcon({ size = 16, strokeWidth = STROKE, ...props }: NucleoIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 18 18"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <line
        x1="4.75"
        y1="5.75"
        x2="4.75"
        y2="12.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <path
        d="M13.25,5.75v1c0,1.105-.895,2-2,2H6.75c-1.105,0-2,.895-2,2"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></path>
      <circle
        cx="4.75"
        cy="3.75"
        r="2"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></circle>
      <circle
        cx="13.25"
        cy="3.75"
        r="2"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></circle>
      <circle
        cx="4.75"
        cy="14.25"
        r="2"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></circle>
    </svg>
  );
}
