#!/usr/bin/env bun
/**
 * Regenerates `generated/` from the installed `codex` binary:
 *
 *   bun apps/daemon/src/harness/codex/generate.ts [--codex /path/to/codex]
 *
 * It runs `codex app-server generate-ts` (the stable surface, no
 * `--experimental`) into a temp directory, keeps only the import closure of the
 * protocol types the Codex driver uses, formats them with Biome, and records the
 * Codex version in `generated/version.ts`. After
 * regenerating, `bun run typecheck` fails wherever the hand-written runtime
 * schemas in `protocol.ts` no longer match the new types.
 */
import { mkdtempSync, rmSync } from "node:fs"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { dirname, join, relative, resolve } from "node:path"

/** The protocol types the driver sends, receives or validates, relative to the generate-ts root. */
const ROOTS = [
  "RequestId",
  "InitializeParams",
  "InitializeResponse",
  "ServerRequest",
  "v2/ThreadStartParams",
  "v2/ThreadStartResponse",
  "v2/ThreadResumeParams",
  "v2/ThreadResumeResponse",
  "v2/ThreadUnsubscribeParams",
  "v2/ThreadUnsubscribeResponse",
  "v2/TurnStartParams",
  "v2/TurnStartResponse",
  "v2/TurnSteerParams",
  "v2/TurnSteerResponse",
  "v2/TurnInterruptParams",
  "v2/TurnInterruptResponse",
  "v2/ThreadNameUpdatedNotification",
  "v2/TurnStartedNotification",
  "v2/TurnCompletedNotification",
  "v2/TurnPlanUpdatedNotification",
  "v2/ItemStartedNotification",
  "v2/ItemCompletedNotification",
  "v2/AgentMessageDeltaNotification",
  "v2/PlanDeltaNotification",
  "v2/ReasoningSummaryTextDeltaNotification",
  "v2/ReasoningTextDeltaNotification",
  "v2/CommandExecutionOutputDeltaNotification",
  "v2/ServerRequestResolvedNotification",
  "v2/ErrorNotification",
  "v2/CommandExecutionRequestApprovalResponse",
  "v2/FileChangeRequestApprovalResponse",
  "v2/PermissionsRequestApprovalResponse",
  "v2/ToolRequestUserInputResponse",
  "v2/McpServerElicitationRequestResponse",
]

const here = import.meta.dir
const outDir = join(here, "generated")

const args = process.argv.slice(2)
const codexFlag = args.indexOf("--codex")
const codex = codexFlag >= 0 ? args[codexFlag + 1] : Bun.which("codex")
if (!codex) throw new Error("codex not found on PATH; pass --codex /path/to/codex")

const run = async (argv: ReadonlyArray<string>): Promise<string> => {
  const proc = Bun.spawn([...argv], { stdout: "pipe", stderr: "pipe" })
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ])
  if (code !== 0) throw new Error(`${argv.join(" ")} exited ${code}: ${err}`)
  return out
}

const version = (await run([codex, "--version"])).trim().replace(/^codex-cli\s+/, "")
const scratch = mkdtempSync(join(tmpdir(), "polaris-codex-gen-"))
try {
  await run([codex, "app-server", "generate-ts", "--out", scratch])

  const importPattern = /from "(\.{1,2}\/[^"]+)"/g
  const seen = new Set<string>()
  const queue = [...ROOTS]
  while (queue.length > 0) {
    const id = queue.pop()!
    if (seen.has(id)) continue
    seen.add(id)
    const source = await readFile(join(scratch, `${id}.ts`), "utf8")
    for (const match of source.matchAll(importPattern)) {
      const target = relative(scratch, resolve(dirname(join(scratch, id)), match[1]!))
      if (!seen.has(target)) queue.push(target)
    }
  }

  rmSync(outDir, { recursive: true, force: true })
  for (const id of [...seen].sort()) {
    const source = await readFile(join(scratch, `${id}.ts`), "utf8")
    const target = join(outDir, `${id}.ts`)
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, source)
  }

  const exportName = (id: string) => id.split("/").at(-1)!
  const index = [
    "// Generated by generate.ts. Do not edit.",
    ...ROOTS.map((id) => `export type { ${exportName(id)} } from "./${id}.ts"`),
    `export type { ThreadItem } from "./v2/ThreadItem.ts"`,
    `export type { UserInput } from "./v2/UserInput.ts"`,
    `export type { AskForApproval } from "./v2/AskForApproval.ts"`,
    `export type { SandboxMode } from "./v2/SandboxMode.ts"`,
    `export type { SandboxPolicy } from "./v2/SandboxPolicy.ts"`,
    `export type { ApprovalsReviewer } from "./v2/ApprovalsReviewer.ts"`,
    "",
  ].join("\n")
  await writeFile(join(outDir, "index.ts"), index)
  await writeFile(
    join(outDir, "version.ts"),
    `// Generated by generate.ts. Do not edit.\n/** The \`codex --version\` these bindings were generated from. */\nexport const GENERATED_FROM_CODEX_VERSION = ${JSON.stringify(version)}\n`,
  )
  await run(["bunx", "biome", "check", "--write", outDir])
  console.log(
    `generated ${seen.size} files from codex ${version} into ${relative(process.cwd(), outDir)}`,
  )
} finally {
  rmSync(scratch, { recursive: true, force: true })
}
